title: frncscrlnd's writeups
markdown: kramdown
theme: minima
permalink: pretty

collections:
  tryhackme:
    output: true
    permalink: /tryhackme/:path/
  yamagata_xss:
    output: true
    permalink: /xss21/:path/
