title: frncscrlnd's writeups
markdown: kramdown
theme: jekyll-theme-midnight
permalink: pretty

baseurl: "/writeups"  
url: "https://tuo-username.github.io" 

collections:
  tryhackme:
    output: true
    permalink: /tryhackme/:title/
  yamagata_xss:
    output: true
    permalink: /xss/:title/

  include:
- _tryhackme/**/images/**/*
- _yamagata_xss/**/images/**/*
- _tryhackme/**/files/**/*
- _yamagata_xss/**/files/**/*