title: frncscrlnd's writeups
markdown: kramdown
permalink: pretty

collections:
  tryhackme:
    output: true
    permalink: /tryhackme/:path/
  yamagata_xss:
    output: true
    permalink: /xss21/:path/

remote_theme: abhinavs/moonwalk

moonwalk:
  dark_mode: true
  show_description: true
  show_post_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag