title: frncscrlnd's writeups
theme: minima
markdown: kramdown
permalink: pretty

collections:
  tryhackme:
    output: true
    permalink: /tryhackme/:path/
  yamagata_xss:
    output: true
    permalink: /xss21/:path/

