title: frncscrlnd's writeups
markdown: kramdown
theme: minima
permalink: pretty

collections:
  tryhackme:
    output: true
    permalink: writeups/tryhackme/:title/
  yamagata_xss:
    output: true
    permalink: writeups/xss21/:title/

include:
  - _tryhackme/images/**/*
  - _xss_challenges/images/**/*
