title: frncscrlnd's writeups
markdown: kramdown
theme: jekyll-theme-midnight
permalink: pretty

collections:
  tryhackme:
    output: true
    permalink: /writeups/tryhackme/:title/
  yamagata_xss:
    output: true
    permalink: /writeups/xss/:title/

defaults:
  - scope:
      path: ""
      type: tryhackme
    values:
      layout: page
  - scope:
      path: ""
      type: yamagata_xss
    values:
      layout: page

include:
  - _tryhackme/images/**/*
  - _xss_challenges/images/**/*
