title: frncscrlnd's writeups
markdown: kramdown
theme: jekyll-theme-midnight
permalink: pretty

plugins:
  - jekyll-sitemap

baseurl: "/writeups"  
url: "https://frncscrlnd.github.io" 

collections:
  tryhackme:
    output: true
    permalink: /tryhackme/:title/
  hackthebox:
    output: true
    permalink: /hackthebox/:title
  yamagata_xss:
    output: true
    permalink: /yamagata_xss/:title/
  y0n3uchy_xss:
    output: true
    permalink: /y0n3uchy_xss/:title/
  bandit:
    output: true
    permalink: /bandit/:title/
  cryptopals:
    output: true
    permalink: /cryptopals/:title
  try2hack:
    output: true
    permalink: /try2hack/:title


